[package]
name = "file-sensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.0.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_yaml = "0.9.13"