pipeline_name:
  - test:
    folder_nesting_sequence:
      - salmon_index
      - strandness
    upload_target:
      - fastq
  - test2:
    folder_nesting_sequence2:
      - salmon_index
      - strandness
    upload_target2:
      - fastq
